# Chapter 3. 파이토치로 구현하는 ANN
----
## 1) 텐서와 Autograd
### __텐서(Tensor)__란 무엇인가?
텐서란, 파이토치에서 다양한 수식을 계산하는 데 사용하는 가장 기본적인 자료구조이다.<br>
텐서에는 차원(랭크)라는 개념이 있다.<br>
- 랭크 0 : 스칼라
- 랭크 1 : 벡터
- 랭크 2 : 2차원 행렬
- 랭크 3 이상 : 3차원 이상 행렬

### 텐서 정의하기

In [2]:
import torch

In [16]:
# 0차원 텐서 = 스칼라
q = torch.tensor(1)
print(q)

tensor(1)


In [15]:
# 1차원 텐서 = 벡터
p = torch.tensor([1,2,3])
print(p)

tensor([1, 2, 3])


In [27]:
# 2차원 텐서 = 2차원 행렬
x = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(x)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [13]:
# 3차원 텐서 = 다차원 행렬
y = torch.tensor([[[1,2,3],[7,8,9]],[[1,2,3],[7,8,9]],[[1,2,3],[7,8,9]]]) # 각 열의 요소 수가 다르면 에러 발생
print(y)

tensor([[[1, 2, 3],
         [7, 8, 9]],

        [[1, 2, 3],
         [7, 8, 9]],

        [[1, 2, 3],
         [7, 8, 9]]])


### 텐서 정보 확인, 수정하기

In [19]:
def printTensor(t):
    print("Size: ", t.size())
    print("Shape: ", t.shape)
    print("Dimension: ", t.ndimension())

In [20]:
printTensor(y)

Size:  torch.Size([3, 2, 3])
Shape:  torch.Size([3, 2, 3])
Dimension:  3


In [21]:
# torch.unsqueeze(tensor, index) : i번째 자리에 차원값 1을 추가한다. 따라서 해당 텐서는 차원이 1 증가한다.
modified_y = torch.unsqueeze(y, 0)
printTensor(modified_y)

Size:  torch.Size([1, 3, 2, 3])
Shape:  torch.Size([1, 3, 2, 3])
Dimension:  4


In [23]:
# torch.squeeze(tesnsor) : 크기가 1인 랭크를 삭제한다. 1인 랭크가 없으면 변화 없음.
modified_y = torch.squeeze(modified_y)
printTensor(modified_y)

Size:  torch.Size([3, 2, 3])
Shape:  torch.Size([3, 2, 3])
Dimension:  3


In [30]:
# tensor.view(n) : 랭크 1의(1차원 벡터) [n]모양으로 바꾸는 함수. 
print(x);
modified_x = x.view(9)
print(modified_x)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [31]:
# 이때, n은 반드시 요소의 개수와 일치해야 한다. 크거나 작으면 에러.
try:
    modified_x = x.view(2,4)
except Exception as e:
    print(e)

shape '[2, 4]' is invalid for input of size 9


### 정리
텐서를 수정하는 함수들은 기존에 존재하던 요소를 건들이지 않으면서 텐서의 모양만 수정한다.<br>
따라서 기존 요소를 지우거나, 허용되지 않은 방법으로 요소를 늘린다면 에러가 발생한다.
- torch.squeeze(tensor, index) : i번째 자리에 크기가 1인 차원을 하나 추가한다.
- torch.unsqueeze(tensor) : 크기가 1인 차원을 삭제한다.
- tensor.view(num of element) : 다차원 행렬을 1차원 벡터로 변환한다. 파라미터는 반드시 요소의 개수와 일치해야 한다.